USE second_hand_book;

INSERT INTO books (title, author, price, cover, description, seller_id, status, created_at) VALUES
('Python编程：从入门到实践', 'Eric Matthes', 65.00, '/picture/tech-book.svg', 'Python入门首选，涵盖基础与项目实战', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 10 DAY)),
('活着', '余华', 28.00, '/picture/novel-book.svg', '讲述人如何去承受巨大的苦难', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 12 DAY)),
('设计模式：可复用面向对象软件的基础', 'GoF', 45.00, '/picture/tech-book.svg', '软件工程领域的圣经', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 15 DAY)),
('百年孤独', '加西亚·马尔克斯', 39.50, '/picture/novel-book.svg', '魔幻现实主义文学代表作', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 20 DAY)),
('写给大家看的设计书', 'Robin Williams', 35.00, '/picture/art-book.svg', '普及设计原则的经典之作', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Head First Java', 'Kathy Sierra', 58.00, '/picture/tech-book.svg', '轻松有趣的Java入门书', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 2 DAY)),
('解忧杂货店', '东野圭吾', 32.00, '/picture/novel-book.svg', '温暖人心的奇幻故事', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 8 DAY)),
('点石成金：访客至上的Web设计秘笈', 'Steve Krug', 42.00, '/picture/art-book.svg', '可用性设计的经典', 3, 'sold', DATE_SUB(NOW(), INTERVAL 30 DAY)),
('Effective C++', 'Scott Meyers', 55.00, '/picture/tech-book.svg', '改善程序与设计的55个具体做法', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 25 DAY)),
('追风筝的人', '卡勒德·胡赛尼', 29.00, '/picture/novel-book.svg', '为你，千千万万遍', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 18 DAY)),
('Clean Code', 'Robert C. Martin', 62.00, '/picture/tech-book.svg', '代码整洁之道', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 3 DAY)),
('平凡的世界', '路遥', 88.00, '/picture/novel-book.svg', '展现了中国70年代中期到80年代中期的城乡社会生活', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 22 DAY)),
('色彩设计的原理', '伊达千代', 38.00, '/picture/art-book.svg', '零基础学配色的好书', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 14 DAY)),
('Vue.js设计与实现', '霍春阳', 79.00, '/picture/tech-book.svg', '深入理解Vue.js内部机制', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 7 DAY)),
('白夜行', '东野圭吾', 35.00, '/picture/novel-book.svg', '绝望的念想，悲恸的守望', 5, 'sold', DATE_SUB(NOW(), INTERVAL 40 DAY)),
('艺术的故事', '贡布里希', 128.00, '/picture/art-book.svg', '有关艺术历史的经典著作', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 28 DAY)),
('深入浅出MySQL', '网易技术部', 59.00, '/picture/tech-book.svg', '数据库开发人员必读', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 6 DAY)),
('小王子', '圣埃克苏佩里', 22.00, '/picture/novel-book.svg', '献给大人的童话', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 9 DAY)),
('版式设计原理', '佐佐木刚士', 48.00, '/picture/art-book.svg', '版式设计基础入门', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 11 DAY)),
('Spring Boot实战', 'Craig Walls', 68.00, '/picture/tech-book.svg', 'Spring Boot开发指南', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 4 DAY)),
('1984', '乔治·奥威尔', 26.00, '/picture/novel-book.svg', '反乌托邦文学经典', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 35 DAY)),
('黑客与画家', 'Paul Graham', 49.00, '/picture/tech-book.svg', '硅谷创业教父的文集', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 13 DAY)),
('月亮与六便士', '毛姆', 28.00, '/picture/novel-book.svg', '满地都是六便士，他却抬头看见了月亮', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 16 DAY)),
('字型之不思議', '小林章', 45.00, '/picture/art-book.svg', '西文字体设计的奥秘', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 21 DAY)),
('Redis设计与实现', '黄健宏', 65.00, '/picture/tech-book.svg', '全面剖析Redis', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 19 DAY)),
('局外人', '加缪', 24.00, '/picture/novel-book.svg', '存在主义文学代表作', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 29 DAY)),
('TCP/IP详解 卷1', 'W. Richard Stevens', 85.00, '/picture/tech-book.svg', '网络协议经典教材', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 1 DAY)),
('人间失格', '太宰治', 20.00, '/picture/novel-book.svg', '生而为人，我很抱歉', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 33 DAY)),
('交互设计之路', 'Alan Cooper', 52.00, '/picture/art-book.svg', '让高科技产品回归人性', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 26 DAY)),
('Go语言圣经', 'Alan A. A. Donovan', 75.00, '/picture/tech-book.svg', 'Go语言权威教程', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 8 DAY)),
('霍乱时期的爱情', '加西亚·马尔克斯', 38.00, '/picture/novel-book.svg', '一段跨越半个多世纪的爱情史诗', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 31 DAY)),
('Kubernetes权威指南', '龚正', 99.00, '/picture/tech-book.svg', '容器编排实战', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 5 DAY)),
('罗生门', '芥川龙之介', 23.00, '/picture/novel-book.svg', '人性的罗生门', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 14 DAY)),
('平面设计中的网格系统', 'Josef Müller-Brockmann', 68.00, '/picture/art-book.svg', '设计类专业必读', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 24 DAY)),
('鸟哥的Linux私房菜', '鸟哥', 78.00, '/picture/tech-book.svg', 'Linux入门红宝书', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 17 DAY)),
('麦田里的守望者', '塞林格', 27.00, '/picture/novel-book.svg', '青春期的迷惘与反抗', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 38 DAY)),
('React进阶之路', '徐超', 59.00, '/picture/tech-book.svg', 'React开发实战', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 12 DAY)),
('挪威的森林', '村上春树', 32.00, '/picture/novel-book.svg', '百分百的恋爱小说', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 23 DAY)),
('启示录', 'Marty Cagan', 46.00, '/picture/art-book.svg', '打造用户喜爱的产品', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 27 DAY)),
('Docker技术入门与实战', '杨保华', 55.00, '/picture/tech-book.svg', '容器技术快速入门', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 10 DAY)),
('围城', '钱钟书', 29.00, '/picture/novel-book.svg', '城外的人想冲进去，城里的人想逃出来', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 36 DAY)),
('高性能MySQL', 'Baron Schwartz', 88.00, '/picture/tech-book.svg', 'MySQL调优指南', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 9 DAY)),
('许三观卖血记', '余华', 26.00, '/picture/novel-book.svg', '关于生存的现实主义力作', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 15 DAY)),
('About Face 4: 交互设计精髓', 'Alan Cooper', 98.00, '/picture/art-book.svg', '交互设计领域的百科全书', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 32 DAY)),
('Flutter实战', '温铭', 65.00, '/picture/tech-book.svg', '跨平台移动开发', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 18 DAY)),
('边城', '沈从文', 22.00, '/picture/novel-book.svg', '湘西世界的田园牧歌', 1, 'onsale', DATE_SUB(NOW(), INTERVAL 20 DAY)),
('浪潮之巅', '吴军', 58.00, '/picture/tech-book.svg', 'IT行业的兴衰史', 2, 'onsale', DATE_SUB(NOW(), INTERVAL 11 DAY)),
('嫌疑人X的献身', '东野圭吾', 33.00, '/picture/novel-book.svg', '逻辑与情感的较量', 3, 'onsale', DATE_SUB(NOW(), INTERVAL 28 DAY)),
('字体设计演进', '王受之', 42.00, '/picture/art-book.svg', '字体设计的历史与未来', 4, 'onsale', DATE_SUB(NOW(), INTERVAL 34 DAY)),
('Node.js实战', 'Mike Cantelon', 62.00, '/picture/tech-book.svg', 'Node.js后端开发', 5, 'onsale', DATE_SUB(NOW(), INTERVAL 7 DAY));
